---
abstract: "Perl extension for basic validation of\nNorth American Vehicle Identification Numbers from 1980 and later"
author:
  - 'collin seaton <cseaton@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-VIN
provides:
  Validate::VIN:
    file: lib/Data/Validate/VIN.pm
    version: 0.02
requires:
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
